import json
from pathlib import Path

translations = {
    # sprint1
    "### SPRINT 1": "### SPRINT 1",
    "#### Pesquisar APIs de dados financeiros": "#### Research financial data APIs",
    "Seguem abaixo as principais APIs para captura de dados financeiros:": "Below are the main APIs for capturing financial data:",
    "Oferece dados financeiros globais, incluindo ações, forex, criptomoedas e indicadores econômicos. Possui uma API gratuita com limites de uso.": "Provides global financial data including stocks, forex, cryptocurrencies, and economic indicators. It has a free API with usage limits.",
    "# Biblioteca responsável pela atualização automática da página web": "# Library responsible for automatic page refresh",
    "Disponibiliza dados financeiros globais, com uma API gratuita e planos pagos para dados mais avançados.": "Provides global financial data with a free API and paid plans for more advanced data.",
    "Oferece uma vasta gama de dados financeiros, incluindo ações, moedas, commodities e indicadores econômicos. Possui planos gratuitos e pagos.": "Offers a wide range of financial data including stocks, currencies, commodities, and economic indicators. It has free and paid plans.",
    "Muito popular para dados históricos e atuais de ações, criptomoedas e outras informações financeiras.": "Very popular for historical and current stock data, cryptocurrencies, and other financial information.",
    "A B3 (Bolsa de Valores do Brasil) oferece algumas APIs para acesso a dados financeiros. Embora algumas sejam pagas, há informações públicas disponíveis.": "B3 (Brazil Stock Exchange) offers some APIs for accessing financial data. Although some are paid, public information is available.",
    "Não possui uma biblioteca oficial em Python, mas você pode usar requests para fazer chamadas HTTP.": "It does not have an official Python library, but you can use requests to make HTTP calls.",
    "Oferece dados de mercado de vários países, incluindo o Brasil. Para acessar a API, geralmente é necessário web scraping.": "Offers market data from several countries, including Brazil. Accessing the API usually requires web scraping.",
    "Biblioteca Python: investpy (mas verifique se ainda está funcionando, pois houve bloqueios recentes).": "Python library: investpy (but check if it is still working, as there have been recent blocks).",
    "Para o ambiente de desenvolvimento optei por utilizar o sistema operacional Windows 11, para escrita do código utilizei o Visual Studio Code (VScode) com a extensão do Jupyter Notebook e do python como linguagem de programação, conforme imagens abaixo:": "For the development environment I chose to use Windows 11, and I wrote the code using Visual Studio Code with the Jupyter Notebook and Python extensions, as shown in the images below:",
    "Para controle de versão estou utilizando o git com Github gerenciado através de linha de comando com o Cmder conforme imagens abaixo:": "For version control I am using Git with GitHub managed through the command line using Cmder, as shown in the images below:",
    "#### Para criação da interface do usuário utilizaremos o Framework python Streamlit": "#### To create the user interface we will use the Python framework Streamlit",
    "#bliblioteca responsável pela atualização automática da página web": "# Library responsible for automatic page refresh",
    "##### Optei em utilizar o Yahoo Finance por sua flexibilidade e por ser gratuito, sendo uma excelente opção para criação do protótipo, na minha opinião.": "##### I chose to use Yahoo Finance for its flexibility and because it is free, making it an excellent option for building the prototype in my opinion.",
    "# Importando bibliotecas para manipulação de datas": "# Importing libraries for date manipulation",
    "# Importando biblioteca para exibir gráficos interativos": "# Importing library to display interactive charts",
    "##### Criando o script inicial da aplicação e realizando testes": "##### Creating the initial application script and running tests",
    "# Lista de países e intervalos de tempo disponíveis": "# List of available countries and time intervals",
    "# Criando filtros padrão para o intervalo de pesquisa (últimos 30 dias)": "# Creating default filters for the search range (last 30 days)",
    "# Função com cache do Streamlit para evitar requisições redundantes aos dados": "# Streamlit cached function to avoid redundant data requests",
    "    \"\"\"Busca dados históricos de ações do Yahoo Finance.\"\"\"": "    \"\"\"Fetches historical stock data from Yahoo Finance.\"\"\"",
    "# Função para formatar objeto datetime em string": "# Function to format a datetime object as a string",
    "# Função que cria um gráfico de candlestick para visualização de dados OHLC": "# Function that creates a candlestick chart for OHLC data visualization",
    "    \"\"\"Cria um gráfico de candlestick interativo a partir de dados OHLC.\"\"\"": "    \"\"\"Creates an interactive candlestick chart from OHLC data.\"\"\"",
    "# Construindo a barra lateral da página web com controles de seleção": "# Building the page sidebar with selection controls",
    "# Contêineres para renderização dinâmica dos gráficos": "# Containers for dynamic chart rendering",
    "# Definindo título e cabeçalhos iniciais da página com fontes menores": "# Defining initial page title and headers with smaller fonts",
    "st.markdown(\"# Análise Gráfica de Ações em Tempo Real\")": "st.markdown(\"# Real-time Stock Chart Analysis\")",
    "st.markdown(\"## Ações\")": "st.markdown(\"## Stocks\")",
    "st.markdown(\"### Análise Gráfica\")": "st.markdown(\"### Chart Analysis\")",
    "# Atualizar página a cada 5 segundos para permitir análise em tempo real": "# Refresh page every 5 seconds to allow real-time analysis",
    "    st.write(\"Contagem é zero\")": "    st.write(\"Count is zero\")",
    "    st.sidebar.error(\"Data Inicial não pode ser maior que Data Final\")": "    st.sidebar.error(\"Start Date cannot be later than End Date\")",
    "        # Exibir gráfico de candlestick": "        # Display candlestick chart",
    "        # Exibir gráfico de linha do preço de fechamento": "        # Display closing price line chart",
    "        st.error(f\"Erro ao carregar dados da ação: {e}\")": "        st.error(f\"Error loading stock data: {e}\")",
    # sprint2
    "#### Testar e implementar a extração de dados": "#### Test and implement data extraction",
    "Exploraremos mais a fundo o Yahoo Finance a fim de realizar mais testes com os dados e atestar a sua confiabilidade e limitações": "We will explore Yahoo Finance in more depth to run additional tests on the data and verify its reliability and limitations",
    "# Importando a biblioteca do Yahoo Finance": "# Importing the Yahoo Finance library",
    "# Importando bibliotecas para manipulação de datas": "# Importing libraries for date manipulation",
    "# Importando biblioteca para exibir gráficos interativos": "# Importing library to display interactive charts",
    "# Importando biblioteca para medir o tempo de execução": "# Importing library to measure execution time",
    "# Importando biblioteca para trabalhar com dataframes": "# Importing library to work with dataframes",
    "# Função para formatar objeto datetime em string": "# Function to format a datetime object as a string",
    "# Função que cria um gráfico de candlestick para visualização de dados OHLC": "# Function that creates a candlestick chart for OHLC data visualization",
    "Com base na função plotCandleStick apresentada acima e um DataFrame local (df),\nrealizaremos alguns testes:": "Based on the plotCandleStick function shown above and a local DataFrame (df), we will perform some tests:",
    "Descrição: Verificar se os dados retornados pela API estão completos e corretos.": "Description: Check whether the data returned by the API is complete and accurate.",
    "Implementação:": "Implementation:",
    "* Simular a captura de dados históricos de uma ação usando a API do Yahoo Finance.": "* Simulate fetching historical stock data using the Yahoo Finance API.",
    "* Verificar se todas as colunas esperadas (Open, Close, High, Low, etc.) estão presentes no DataFrame.": "* Verify that all expected columns (Open, Close, High, Low, etc.) are present in the DataFrame.",
    "* Validar se os dados não possuem valores nulos ou incorretos (exemplo: valores negativos ou muito discrepantes).": "* Validate that the data does not contain null or incorrect values (e.g., negative or highly inconsistent values).",
    "# Criaremos uma função chamada test_integrity e usaremos a ação da Apple (AAPL)": "# We will create a function called test_integrity and use Apple (AAPL) as an example to verify data integrity.",
    "            print(f\"A coluna {col} não está presente no dataframe!\")": "            print(f\"The column {col} is not present in the DataFrame!\")",
    "            print(f\"A coluna {col} contém valores nulos!\")": "            print(f\"The column {col} contains null values!\")",
    "    print(\"Checagem da integridade dos dados concluída.\")": "    print(\"Data integrity check completed.\")",
    "# Baixando os dados com frequência diária da ação da Apple entre 01/01/2023 e 31/12/2023": "# Downloading daily Apple stock data between 01/01/2023 and 12/31/2023",
    "Descrição: Testar a confiabilidade da API em termos de tempo de resposta e consistência dos dados.": "Description: Test the API reliability in terms of response time and data consistency.",
    "* Realizar múltiplas requisições para a mesma ação e período e comparar os resultados para verificar consistência.": "* Perform multiple requests for the same stock and period and compare results to verify consistency.",
    "# Criaremos uma função para testar a confiabilidade dos dados obtidos da API": "# We will create a function to test the reliability of the data obtained from the API",
    "        print(\"Os dados são consistentes através de múltiplas requisições.\")": "        print(\"The data is consistent across multiple requests.\")",
    "        print(\"Inconsistências foram encontradas nos dados para múltiplas requisições!\")": "        print(\"Inconsistencies were found in the data across multiple requests!\")",
    "    print(f\"Tempo levado para a requisição: {end_time - start_time:.2f} segundos\")": "    print(f\"Request duration: {end_time - start_time:.2f} seconds\")",
    "# Usando a ação da Apple (AAPL) entre os dias 1 de janeiro de 2023 e": "# Using Apple (AAPL) between January 1, 2023 and",
    "Utilizaremos a função abaixo para realizar 1000 conexões simultâneas a uma mesma ação": "We will use the function below to perform 1000 simultaneous requests for the same stock",
    "# Criaremos uma função para testar a consistência dos dados obtidos da API": "# We will create a function to test the consistency of the data obtained from the API",
    "        print(f\"Requisição {i + 1}/{num_requests}\")": "        print(f\"Request {i + 1}/{num_requests}\")",
    "    print(f\"Tempo total para {num_requests} requisições: {end_time - start_time:.2f} segundos\")": "    print(f\"Total time for {num_requests} requests: {end_time - start_time:.2f} seconds\")",
    "3. Teste de Limitações da API": "3. API Limitations Test",
    "Descrição: Verificar as limitações da API em termos de períodos de tempo suportados e granularidade dos dados.": "Description: Check the API limitations in terms of supported time periods and data granularity.",
    "Implementação:": "Implementation:",
    "Tentar capturar dados com intervalos de tempo pequenos (como 1m - 1 minuto) ou longos períodos históricos para ver se a API retorna os dados corretamente ou se há alguma limitação.": "Try to fetch data with small intervals (such as 1m - 1 minute) or long historical periods to see if the API returns data correctly or if there is any limitation.",
    "    \"\"\"Testa os limites da API em termos de intervalos pequenos e períodos longos.\"\"\"": "    \"\"\"Tests API limits in terms of small intervals and long periods.\"\"\"",
    "        print(\"Teste 1 - Dados recuperados com sucesso com um intervalo pequeno.\")": "        print(\"Test 1 - Successfully retrieved data with a small interval.\")",
    "        print(\"Teste 2 - com longo período histórico concluído com sucesso.\")": "        print(\"Test 2 - long historical period completed successfully.\")",
    "        print(f\"Erro no Teste 2 - usando um período longo: {e}\")": "        print(f\"Error in Test 2 - using a long period: {e}\")",
    "4. Teste de exibição da API": "4. API display test",
    "Descrição: Verificar se a recuperação de dados histórios da Apple podem ser exibidos graficamente.": "Description: Verify whether the historical data retrieval for Apple can be displayed graphically.",
    "Capturar dados históricos para ver se são exibidos corretamente, para utilizarem os": "Capture historical data to see if it is displayed correctly for use",
    "# Definindo as datas de início e fim": "# Defining start and end dates",
    "# Baixando os dados históricos da Apple (AAPL) usando yfinance": "# Downloading historical Apple (AAPL) data using yfinance",
    "# Plotando o gráfico candlestick": "# Plotting the candlestick chart",
    "# Exibindo o gráfico no Jupyter Notebook": "# Displaying the chart in the Jupyter Notebook",
    "1. Verificação de valores ausentes:": "1. Missing values check:",
    "Eventualmente, os dados podem ter lacunas, especialmente se houver interrupções no mercado ou em dias de feriado, portanto começaremos por verificar se os dados possuem valores ausentes (NaN) no DataFrame testado e decidamos como lidar com eles.": "Data may eventually have gaps, especially if there are market interruptions or holidays, so we will begin by checking whether the data contains missing values (NaN) in the tested DataFrame and decide how to handle them.",
    "2. Verificação de outliers:": "2. Outlier check:",
    "Outliers podem distorcer análises e visualizações, especialmente em alguns tipos de gráficos, para isso identificaremos possíveis outliers usaremos uma técnica estatística chamada IQR (Interquartile Range) para garantir que eles não afetem negativamente a análise.": "Outliers can distort analysis and visualizations, especially for some chart types. For this, we will identify possible outliers using a statistical technique called IQR (Interquartile Range) to ensure they do not negatively affect the analysis.",
    "O IQR é uma medida estatística que representa a diferença entre o terceiro quartil (Q3) e o primeiro quartil (Q1) de um conjunto de dados.": "IQR is a statistical measure that represents the difference between the third quartile (Q3) and the first quartile (Q1) of a dataset.",
    "O que são quartis?": "What are quartiles?",
    "Primeiro Quartil (Q1): É o valor abaixo do qual se encontra 25% dos dados.": "First Quartile (Q1): It is the value below which 25% of the data is found.",
    "Terceiro Quartil (Q3): É o valor abaixo do qual se encontra 75% dos dados.": "Third Quartile (Q3): It is the value below which 75% of the data is found.",
    "Como é calculado?": "How is it calculated?",
    "O IQR é calculado pela fórmula:": "IQR is calculated by the formula:",
    "O IQR é usado principalmente para identificar a dispersão central dos dados e para detectar outliers (valores atípicos). Dados que caem abaixo de 𝑄1 − 1.5 × 𝐼𝑄𝑅 ou acima de 𝑄3 + 1.5 × 𝐼𝑄𝑅 são frequentemente considerados outliers.": "IQR is mainly used to identify the central dispersion of the data and to detect outliers. Data that falls below 𝑄1 − 1.5 × 𝐼𝑄𝑅 or above 𝑄3 + 1.5 × 𝐼𝑄𝑅 is often considered outliers.",
    "# Usando o IQR (Interquartile Range) para detectar outliers no preço de fechamento": "# Using IQR (Interquartile Range) to detect outliers in closing prices",
    "# Remover outliers (opcional, dependendo do tipo de análise)": "# Remove outliers (optional, depending on the analysis type)",
    "3. Verificação de duplicatas:": "3. Duplicate check:",
    "Embora improvável, duplicatas podem ocorrer devido a erros na API ou em requisições repetidas e para evitar isso removeremos quaisquer ocorrência existente para evitar distorções na análise.": "Although unlikely, duplicates may occur due to API errors or repeated requests, and to avoid this we will remove any existing occurrences to prevent distortion in the analysis.",
    "4. Normalização de datas:": "4. Date normalization:",
    "Certificaremos que o intervalo de datas usado esteja alinhado corretamente com os dias de mercado abertos, removendo datas fora do período de trading.": "We will ensure that the date range used is correctly aligned with open market days by removing dates outside the trading period.",
    "# Verificar se as datas são dias úteis (dias de negociação)": "# Check whether the dates are business days (trading days)",
    "5. Reindexação e interpolação:": "5. Reindexing and interpolation:",
    "Podem haver lacunas nas datas, por exemplo, faltando dados em alguns dias úteis e poderemos interpolar ou ajustar os dados, para isto reindexaremos o dataframe para garantir que todas as datas dentro do intervalo estejam presentes e, em seguida, interpolar os dados ausentes, se necessário.": "There may be gaps in the dates, for example missing data on some business days, and we may interpolate or adjust the data. To do this, we will reindex the DataFrame to ensure that all dates within the range are present and then interpolate missing data if necessary.",
    "# Interpolando valores ausentes com interpolação linear": "# Interpolating missing values with linear interpolation",
    "6. Validação final:": "6. Final validation:",
    "Para garantir que, após todas as limpezas e tratamentos, os dados estão consistentes e prontos para análise, faremos uma validação final visualizando um resumo estatístico dos dados e criaremos um gráfico simples para inspecionar a integridade dos dados.": "To ensure that after all cleaning and processing the data is consistent and ready for analysis, we will perform a final validation by viewing a statistical summary of the data and creating a simple chart to inspect data integrity.",
    "# Resumo estatístico dos dados limpos e tratados": "# Statistical summary of cleaned and processed data",
    "# Visualização simples para verificação da integridade dos dados": "# Simple visualization for verifying data integrity",
    "Considerações finais:": "Final considerations:",
    "Embora os dados do Yahoo Finance sejam geralmente confiáveis, essas etapas de limpeza e tratamento garantem que estejamos trabalhando com um conjunto de dados robusto, minimizando possíveis erros ou distorções na análise final.": "Although Yahoo Finance data is generally reliable, these cleaning and processing steps ensure that we are working with a robust dataset, minimizing potential errors or distortions in the final analysis.",
    # sprint3
    "##### ETAPA 1 DO TRELLO - MELHORANDO A INTERFACE GRÁFICA": "##### TRELLO STEP 1 - IMPROVING THE USER INTERFACE",
    "# Importando as bibliotecas necessárias": "# Importing the required libraries",
    "# Criando listas de países, principais ações e intervalos de tempo": "# Creating lists of countries, major stocks, and time intervals",
    "# Criando um dicionário para associar a lista de ações ao país selecionado": "# Creating a dictionary to associate the stock list with the selected country",
    "# Função com cache do Streamlit para evitar requisições redundantes aos dados": "# Streamlit cached function to avoid redundant data requests",
    "    \"\"\"Busca dados históricos de ações do Yahoo Finance.\"\"\"": "    \"\"\"Fetches historical stock data from Yahoo Finance.\"\"\"",
    "# Função para exibição dos gráficos": "# Function for chart display",
    "    \"\"\"Cria um gráfico de candlestick interativo a partir de dados OHLC.\"\"\"": "    \"\"\"Creates an interactive candlestick chart from OHLC data.\"\"\"",
    "# Atualizando a barra lateral para listar as ações de acordo com o país selecionado": "# Updating the sidebar to list stocks according to the selected country",
    "country_select = st.sidebar.selectbox(\"Escolha o país:\", countries)": "country_select = st.sidebar.selectbox(\"Select country:\", countries)",
    "stocks = stock_options[country_select]  # Obtém as ações do país selecionado": "stocks = stock_options[country_select]  # Gets the stocks for the selected country",
    "stock_select = st.sidebar.selectbox(\"Selecione a ação:\", stocks)": "stock_select = st.sidebar.selectbox(\"Select stock:\", stocks)",
    "# Criando o filtro para o usuário selecionar o intervalo de pesquisa desejado": "# Creating filter for the user to select the desired search interval",
    "# Formata as datas no formato brasileiro (DD/MM/YYYY) apenas para exibição": "# Formats dates in Brazilian format (DD/MM/YYYY) for display only",
    "    \"<h1 style='font-size: 24px;'>Análise Gráfica de Ações em Tempo Real</h1>\",": "    \"<h1 style='font-size: 24px;'>Real-time Stock Chart Analysis</h1>\",",
    "# Atualizar página a cada 5 segundos para permitir análise em tempo real": "# Refresh page every 5 seconds to allow real-time analysis",
    "# Verificação de datas e exibição de gráficos": "# Date validation and chart display",
    "##### 1. Validação de Entrada": "##### 1. Input Validation",
    "Validação de datas para garantir que o intervalo seja razoável:": "Date validation to ensure the interval is reasonable:",
    "# Criando os valores padrões para as datas": "# Creating default date values",
    "# Configurando a interface de seleção de datas na barra lateral": "# Configuring the date selection interface in the sidebar",
    "# Verificando se a data inicial é menor que a data final": "# Checking that the start date is earlier than the end date",
    "Impedir múltiplas requisições em um curto espaço de tempo:": "Prevent multiple requests in a short time:",
    "# Função para limitar requisições por tempo": "# Function to limit requests over time",
    "    \"\"\"Verifica se o intervalo mínimo entre requisições foi atendido.\"\"\"": "    \"\"\"Checks that the minimum interval between requests has been met.\"\"\"",
    "    raise ValueError(\"Requisições muito frequentes! Aguarde um momento.\")": "    raise ValueError(\"Requests are too frequent! Please wait a moment.\")",
    "# Variável global para armazenar o tempo da última requisição": "# Global variable to store the time of the last request",
    "# Função para consultar ação com rate limiting e cache": "# Function to query stock data with rate limiting and cache",
    "@st.cache_data(ttl=3600)  # Cache válido por 1 hora": "@st.cache_data(ttl=3600)  # Cache valid for 1 hour",
    "    \"\"\"Busca dados históricos com rate limiting e cache.\"\"\"": "    \"\"\"Fetches historical data with rate limiting and cache.\"\"\"",
    "##### 3. Manejo de Exceções": "##### 3. Exception Handling",
    "    st.error(f\"Erro de Validação: {ve}\")": "    st.error(f\"Validation Error: {ve}\")",
    "##### 4. Validação de Inputs": "##### 4. Input Validation",
    "Embora o Streamlit já lide com a entrada de dados de forma relativamente segura, é bom garantir que os dados recebidos sejam validados para evitar injeção de código malicioso.": "Although Streamlit already handles input relatively safely, it is good to ensure received data is validated to prevent malicious code injection.",
    "Garantindo que a ação selecionada esteja na lista permitida:": "Ensuring that the selected stock is in the allowed list:",
    "# Verificação se o ticker selecionado está na lista permitida": "# Checking if the selected ticker is in the allowed list",
    "    st.sidebar.error(\"Ticker selecionado não é válido!\")": "    st.sidebar.error(\"Selected ticker is not valid!\")",
    "    st.write(f\"Ação selecionada: {stock_select}\")": "    st.write(f\"Selected stock: {stock_select}\")",
    "Implementação de logs:": "Logging implementation:",
    "Implementação de logs para monitorar as atividades e detectar comportamentos anômalos, como acessos frequentes que possam indicar um ataque.": "Implementation of logs to monitor activity and detect anomalous behavior, such as frequent access that may indicate an attack.",
    "logging.info(\"Aplicação iniciada\")": "logging.info(\"Application started\")",
    "##### 7. Manutenção e Atualização": "##### 7. Maintenance and Updates",
    "Agendar uma verificação regular se as bibliotecas utilizadas (como yfinance, streamlit, plotly, etc.) estão atualizadas para se beneficiar de melhorias de segurança e correções de bugs.": "Schedule a regular check to ensure that the libraries used (such as yfinance, streamlit, plotly, etc.) are up to date to benefit from security improvements and bug fixes.",
    "Este item requer verificação manual regular de bibliotecas com o comando pip e deve ser testado antes do deploy.": "This item requires regular manual package checks with the pip command and should be tested before deployment.",
    "# Atualizando as bibliotecas para se beneficiar de melhorias de segurança e correções de bugs": "# Updating libraries to benefit from security improvements and bug fixes",
}

for path in [Path('sprint1.ipynb'), Path('sprint2.ipynb'), Path('sprint3.ipynb')]:
    print('Processing', path)
    data = json.loads(path.read_text(encoding='utf-8'))
    updated = False
    changes = 0
    for cell in data.get('cells', []):
        if cell.get('cell_type') in ('markdown', 'code'):
            new_source = []
            for line in cell.get('source', []):
                text = line.rstrip('\n')
                if text in translations:
                    new_line = translations[text] + ('\n' if line.endswith('\n') else '')
                    if new_line != line:
                        changes += 1
                        updated = True
                    new_source.append(new_line)
                else:
                    new_source.append(line)
            cell['source'] = new_source
    if updated:
        path.write_text(json.dumps(data, ensure_ascii=False, indent=1), encoding='utf-8')
    print('  changes:', changes)
